baseURL = "https://hyoromo.github.io/cluster-craft-item/"
languageCode = "en-us"
title = "hyoromoのclusterクラフトアイテム一覧"
theme = "slate"
googleAnalytics = 'G-7B0DT0V8KF'
publishDir = "docs"

[ params ]
BackgroundStyle = "#303030;"
OpenLinksInNewWindow = true
favicon = true
svg = true
Favicon = "favicon.ico"

# list of nav tags
#[[ params.nav ]]
#name = "おすすめ"
#tag = "favorite"
#icon = "star"

#[[ params.nav ]]
#name = "simple"
#tag = "simple"
#icon = "star"

[[ params.nav ]]
name = "ボクセルフォント"
tag = "voxel_font"
icon = "font"

[[ params.nav ]]
name = "ドットフォント"
tag = "dot_font"
icon = "font"

[[ params.nav ]]
name = "道具"
tag = "tool"
icon = "wrench"

[[ params.nav ]]
name = "おもちゃ"
tag = "toy"
icon = "gamepad"

[[ params.nav ]]
name = "ボクセル"
tag = "voxel"
icon = "cogs"

[[ params.nav ]]
name = "パステル"
tag = "pastel"
icon = "globe"

[[ params.nav ]]
name = "メタリック"
tag = "metallic"
icon = "certificate"

[[ params.nav ]]
name = "透明"
tag = "transparent"
icon = "asterisk"

[[ params.nav ]]
name = "鏡面反射"
tag = "specular_reflection"
icon = "dashboard"

[[ params.nav ]]
name = "椅子"
tag = "chair"
icon = "eject"

[[ params.nav ]]
name = "石造建築セット"
tag = "stone_pack"
icon = "suitcase"

[[ params.nav ]]
name = "アクション"
tag = "action"
icon = "legal"

[[ params.nav ]]
name = "時計"
tag = "clock"
icon = "clock-o"

[[ params.nav ]]
name = "乗り物"
tag = "ride"
icon = "car"

[[ params.nav ]]
name = "画面出力"
tag = "screen"
icon = "tv"

[[ params.nav ]]
name = "扉"
tag = "door"
icon = "key"

[[ params.nav ]]
name = "窓"
tag = "window"
icon = "columns"

[[ params.nav ]]
name = "発光"
tag = "emission"
icon = "magic"

[[ params.nav ]]
name = "食べ物"
tag = "food"
icon = "apple"